In [2]:
import requests
import pandas as pd
import json

In [19]:
url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2018"

querystring = {"page":"0","per_page":"100"}

headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
    'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

response = requests.get(url, headers=headers, params=querystring)

print(response.text[-80:])

l_pages":330,"current_page":1,"next_page":2,"per_page":100,"total_count":32901}}

In [90]:
stl = []
dreb = []
first_name=[]
last_name=[]

for i in range(318):

    url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2020"

    querystring = {"page":i,"per_page":"100"}

    headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
               'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

    result = requests.get(url, headers=headers, params=querystring)
    
    data = result.json()
    
    
    for i in range(len(data['data'])):
        
        stl.append(data['data'][i]['stl'])
        
        dreb.append(data['data'][i]['dreb'])
        
        first_name.append(data['data'][i]['player']['first_name'])
        
        last_name.append(data['data'][i]['player']['last_name'])

TypeError: 'NoneType' object is not subscriptable

In [91]:
df = pd.DataFrame(list(zip(first_name, last_name,stl,dreb)),
               columns =['First_Name', 'Last_Name','stl','dreb'])

In [92]:
df['Player']=df['First_Name']+' '+ df['Last_Name']

In [93]:
df=df[['Player','stl','dreb']]

In [95]:
df=df.groupby(by='Player').mean()

#df['season']='2020'

df

                      stl      dreb
Player
Aaron Gordon     0.625000  4.075000
Aaron Holiday    0.611111  1.037037
Aaron Nesmith    0.166667  0.944444
Abdel Nader      0.263158  1.447368
Adam Mokoka      0.076923  0.115385
...                   ...       ...
Yuta Watanabe    0.384615  1.692308
Zach Collins     0.000000  0.000000
Zach LaVine      0.830189  4.490566
Zeke Nnaji       0.107143  0.767857
Zion Williamson  0.888889  4.537037

[531 rows x 2 columns]

In [103]:
df.reset_index(inplace=True)

In [104]:
kagle = pd.read_csv('all_seasons_2.csv')

In [105]:
kagledf = pd.DataFrame(kagle)

In [106]:
kagledf=kagledf[['player_name','team_abbreviation','age','player_height','country','pts','reb','ast','season']]
kagledf

,player_name,team_abbreviation,age,player_height,country,pts,reb,ast,season
0,Travis Knight,LAL,22.0,213.36,USA,4.8,4.5,0.5,1996-97
1,Matt Fish,MIA,27.0,210.82,USA,0.3,0.8,0.0,1996-97
2,Matt Bullard,HOU,30.0,208.28,USA,4.5,1.6,0.9,1996-97
3,Marty Conlon,BOS,29.0,210.82,USA,7.8,4.4,1.4,1996-97
4,Martin Muursepp,DAL,22.0,205.74,USA,3.7,1.6,0.5,1996-97
...,...,...,...,...,...,...,...,...,...
11695,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,2020-21
11696,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,2020-21
11697,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,2020-21
11698,Marcus Morris Sr.,LAC,31.0,203.20,USA,13.4,4.1,1.0,2020-21
11699,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,2020-21

In [107]:
kagledf = kagledf[kagledf.season == '2020-21']
kagledf

,player_name,team_abbreviation,age,player_height,country,pts,reb,ast,season
11160,Yogi Ferrell,LAC,28.0,182.88,USA,5.6,1.9,2.2,2020-21
11161,Zion Williamson,NOP,20.0,200.66,USA,27.0,7.2,3.7,2020-21
11162,Zeke Nnaji,DEN,20.0,205.74,USA,3.2,1.5,0.2,2020-21
11163,Zach LaVine,CHI,26.0,195.58,USA,27.4,5.0,4.9,2020-21
11164,Yuta Watanabe,TOR,26.0,205.74,Japan,4.4,3.2,0.8,2020-21
...,...,...,...,...,...,...,...,...,...
11695,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,2020-21
11696,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,2020-21
11697,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,2020-21
11698,Marcus Morris Sr.,LAC,31.0,203.20,USA,13.4,4.1,1.0,2020-21
11699,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,2020-21

In [108]:
final=pd.merge(kagledf,df,how='inner',left_on='player_name',right_on='Player')

In [109]:
final=final[['Player','team_abbreviation','age','player_height','country','pts','reb','ast','stl','dreb','season']]

In [110]:
final

,Player,team_abbreviation,age,player_height,country,pts,reb,ast,stl,dreb,season
0,Yogi Ferrell,LAC,28.0,182.88,USA,5.6,1.9,2.2,1.500000,2.000000,2020-21
1,Zion Williamson,NOP,20.0,200.66,USA,27.0,7.2,3.7,0.888889,4.537037,2020-21
2,Zeke Nnaji,DEN,20.0,205.74,USA,3.2,1.5,0.2,0.107143,0.767857,2020-21
3,Zach LaVine,CHI,26.0,195.58,USA,27.4,5.0,4.9,0.830189,4.490566,2020-21
4,Yuta Watanabe,TOR,26.0,205.74,Japan,4.4,3.2,0.8,0.384615,1.692308,2020-21
...,...,...,...,...,...,...,...,...,...,...,...
517,Matt Thomas,UTA,26.0,193.04,USA,3.1,1.0,0.4,0.053571,0.464286,2020-21
518,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,0.222222,1.222222,2020-21
519,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,0.188679,0.679245,2020-21
520,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,0.104167,0.479167,2020-21
521,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,0.625000,4.075000,2020-21