In [1]:
import requests
import pandas as pd
import json

In [25]:
stl = []
dreb = []
first_name=[]
last_name=[]
season=[]

for i in range(331):

    url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2018"

    querystring = {"page":i,"per_page":"100"}

    headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
               'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

    result = requests.get(url, headers=headers, params=querystring)
    
    data = result.json()
    
    for e in range(len(data['data'])):
        
        stl.append(data['data'][e]['stl'])
        
        dreb.append(data['data'][e]['dreb'])
        
        first_name.append(data['data'][e]['player']['first_name'])
        
        last_name.append(data['data'][e]['player']['last_name'])
        
        season.append(data['data'][e]['game']['season'])

TypeError: 'NoneType' object is not subscriptable

In [27]:
df = pd.DataFrame(list(zip(first_name, last_name,stl,dreb)),
               columns =['First_Name', 'Last_Name','stl','dreb'])

df['Player']=df['First_Name']+' '+ df['Last_Name']

df=df[['Player','stl','dreb']]

df=df.groupby(by='Player').mean()

df['season']='2018'

df

                   stl      dreb season
Player
Aaron Gordon       1.0  3.666667   2018
Aaron Holiday      0.5  0.500000   2018
Abdel Nader        0.0  1.000000   2018
Al Horford         2.0  4.800000   2018
Al-Farouq Aminu    0.0  5.000000   2018
...                ...       ...    ...
Willy Hernangomez  0.0  0.500000   2018
Yogi Ferrell       1.0  1.500000   2018
Zach Collins       2.0  6.000000   2018
Zach LaVine        1.0  4.000000   2018
Zaza Pachulia      0.0  0.000000   2018

[380 rows x 3 columns]

In [28]:

for b in range(289):

    url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2019"

    querystring = {"page":b,"per_page":"100"}
    headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
               'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

    result = requests.get(url, headers=headers, params=querystring)
    
    data = result.json()
    
    for c in range(len(data['data'])):
        
        stl.append(data['data'][c]['stl'])
        
        dreb.append(data['data'][c]['dreb'])
        
        first_name.append(data['data'][c]['player']['first_name'])
        
        last_name.append(data['data'][c]['player']['last_name'])
        
        season.append(data['data'][c]['game']['season'])

In [30]:
df1 = pd.DataFrame(list(zip(first_name, last_name,stl,dreb)),
               columns =['First_Name', 'Last_Name','stl','dreb'])

df1['Player']=df1['First_Name']+' '+ df1['Last_Name']

df1=df1[['Player','stl','dreb']]

df1=df1.groupby(by='Player').mean()

df1['season']='2019'

df1

                        stl      dreb season
Player
Aaron Gordon       0.893939  3.424242   2019
Aaron Holiday      0.814815  2.987654   2019
Abdel Nader        0.388889  1.847222   2019
Adam Mokoka        0.666667  1.333333   2019
Admiral Schofield  0.441860  1.511628   2019
...                     ...       ...    ...
Zach Norvell Jr.   0.142857  0.142857   2019
Zaza Pachulia      0.000000  0.000000   2019
Zhaire Smith       0.300000  1.100000   2019
Zion Williamson    0.960000  4.080000   2019
Zylan Cheatham     0.666667  2.000000   2019

[592 rows x 3 columns]

In [31]:
for d in range(318):

    url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2020"

    querystring = {"page":d,"per_page":"100"}

    headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
               'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

    result = requests.get(url, headers=headers, params=querystring)
    
    data = result.json()
    
    for x in range(len(data['data'])):
        
        stl.append(data['data'][x]['stl'])
        
        dreb.append(data['data'][x]['dreb'])
        
        first_name.append(data['data'][x]['player']['first_name'])
        
        last_name.append(data['data'][x]['player']['last_name'])
        
        season.append(data['data'][x]['game']['season'])

TypeError: 'NoneType' object is not subscriptable

In [32]:
df2 = pd.DataFrame(list(zip(first_name, last_name,stl,dreb)),
               columns =['First_Name', 'Last_Name','stl','dreb'])

df2['Player']=df2['First_Name']+' '+ df2['Last_Name']

df2=df2[['Player','stl','dreb']]

df2=df2.groupby(by='Player').mean()

df2['season']='2020'

df2

                      stl      dreb season
Player
Aaron Gordon     0.783019  3.320755   2020
Aaron Holiday    0.814815  2.711111   2020
Aaron Nesmith    0.277778  1.518519   2020
Abdel Nader      0.327273  1.854545   2020
Adam Mokoka      0.431818  1.045455   2020
...                   ...       ...    ...
Zaza Pachulia    0.000000  0.000000   2020
Zeke Nnaji       0.232143  0.714286   2020
Zhaire Smith     0.300000  1.100000   2020
Zion Williamson  0.708861  3.924051   2020
Zylan Cheatham   0.666667  2.000000   2020

[685 rows x 3 columns]

In [57]:
dftest=pd.merge(df,df1,how='inner',left_on='Player',right_on='Player')

In [79]:
dftest

                   stl_x    dreb_x season_x     stl_y    dreb_y season_y
Player
Aaron Gordon         1.0  3.666667     2018  0.893939  3.424242     2019
Aaron Holiday        0.5  0.500000     2018  0.814815  2.987654     2019
Abdel Nader          0.0  1.000000     2018  0.388889  1.847222     2019
Al Horford           2.0  4.800000     2018  0.653846  4.628205     2019
Al-Farouq Aminu      0.0  5.000000     2018  0.950000  2.150000     2019
...                  ...       ...      ...       ...       ...      ...
Willy Hernangomez    0.0  0.500000     2018  0.434783  1.710145     2019
Yogi Ferrell         1.0  1.500000     2018  0.513514  2.067568     2019
Zach Collins         2.0  6.000000     2018  0.600000  3.000000     2019
Zach LaVine          1.0  4.000000     2018  0.671875  3.968750     2019
Zaza Pachulia        0.0  0.000000     2018  0.000000  0.000000     2019

[380 rows x 6 columns]

In [58]:
dftest1=pd.merge(dftest,df2,how='inner',left_on='Player',right_on='Player')

In [59]:
dftest1

,stl_x,dreb_x,season_x,stl_y,dreb_y,season_y,stl,dreb,season
Player,,,,,,,,,
Aaron Gordon,1.0,3.666667,2018,0.893939,3.424242,2019,0.783019,3.320755,2020
Aaron Holiday,0.5,0.500000,2018,0.814815,2.987654,2019,0.814815,2.711111,2020
Abdel Nader,0.0,1.000000,2018,0.388889,1.847222,2019,0.327273,1.854545,2020
Al Horford,2.0,4.800000,2018,0.653846,4.628205,2019,0.612613,4.639640,2020
Al-Farouq Aminu,0.0,5.000000,2018,0.950000,2.150000,2019,0.673077,2.192308,2020
...,...,...,...,...,...,...,...,...,...
Willy Hernangomez,0.0,0.500000,2018,0.434783,1.710145,2019,0.488189,1.905512,2020
Yogi Ferrell,1.0,1.500000,2018,0.513514,2.067568,2019,0.513158,2.065789,2020
Zach Collins,2.0,6.000000,2018,0.600000,3.000000,2019,0.333333,1.550000,2020
Zach LaVine,1.0,4.000000,2018,0.671875,3.968750,2019,0.709402,4.282051,2020
Zaza Pachulia,0.0,0.000000,2018,0.000000,0.000000,2019,0.000000,0.000000,2020

In [60]:
dftest1.reset_index(inplace=True)

In [61]:
dftest1

,Player,stl_x,dreb_x,season_x,stl_y,dreb_y,season_y,stl,dreb,season
0,Aaron Gordon,1.0,3.666667,2018,0.893939,3.424242,2019,0.783019,3.320755,2020
1,Aaron Holiday,0.5,0.500000,2018,0.814815,2.987654,2019,0.814815,2.711111,2020
2,Abdel Nader,0.0,1.000000,2018,0.388889,1.847222,2019,0.327273,1.854545,2020
3,Al Horford,2.0,4.800000,2018,0.653846,4.628205,2019,0.612613,4.639640,2020
4,Al-Farouq Aminu,0.0,5.000000,2018,0.950000,2.150000,2019,0.673077,2.192308,2020
...,...,...,...,...,...,...,...,...,...,...
375,Willy Hernangomez,0.0,0.500000,2018,0.434783,1.710145,2019,0.488189,1.905512,2020
376,Yogi Ferrell,1.0,1.500000,2018,0.513514,2.067568,2019,0.513158,2.065789,2020
377,Zach Collins,2.0,6.000000,2018,0.600000,3.000000,2019,0.333333,1.550000,2020
378,Zach LaVine,1.0,4.000000,2018,0.671875,3.968750,2019,0.709402,4.282051,2020
379,Zaza Pachulia,0.0,0.000000,2018,0.000000,0.000000,2019,0.000000,0.000000,2020

In [94]:
kagle = pd.read_csv('all_seasons_2.csv')

In [95]:
kagledf = pd.DataFrame(kagle)

In [96]:
kagledf=kagledf[['player_name','team_abbreviation','age','player_height','country','pts','reb','ast','season']]
kagledf

,player_name,team_abbreviation,age,player_height,country,pts,reb,ast,season
0,Travis Knight,LAL,22.0,213.36,USA,4.8,4.5,0.5,1996-97
1,Matt Fish,MIA,27.0,210.82,USA,0.3,0.8,0.0,1996-97
2,Matt Bullard,HOU,30.0,208.28,USA,4.5,1.6,0.9,1996-97
3,Marty Conlon,BOS,29.0,210.82,USA,7.8,4.4,1.4,1996-97
4,Martin Muursepp,DAL,22.0,205.74,USA,3.7,1.6,0.5,1996-97
...,...,...,...,...,...,...,...,...,...
11695,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,2020-21
11696,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,2020-21
11697,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,2020-21
11698,Marcus Morris Sr.,LAC,31.0,203.20,USA,13.4,4.1,1.0,2020-21
11699,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,2020-21

In [97]:
kagledf.dtypes

player_name           object
team_abbreviation     object
age                  float64
player_height        float64
country               object
pts                  float64
reb                  float64
ast                  float64
season                object
dtype: object

In [93]:
kagledf = kagledf[kagledf['season'].str.contains('2020-21')]

kagledf

,player_name,team_abbreviation,age,player_height,country,pts,reb,ast,season
11160,Yogi Ferrell,LAC,28.0,182.88,USA,5.6,1.9,2.2,2020-21
11161,Zion Williamson,NOP,20.0,200.66,USA,27.0,7.2,3.7,2020-21
11162,Zeke Nnaji,DEN,20.0,205.74,USA,3.2,1.5,0.2,2020-21
11163,Zach LaVine,CHI,26.0,195.58,USA,27.4,5.0,4.9,2020-21
11164,Yuta Watanabe,TOR,26.0,205.74,Japan,4.4,3.2,0.8,2020-21
...,...,...,...,...,...,...,...,...,...
11695,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,2020-21
11696,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,2020-21
11697,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,2020-21
11698,Marcus Morris Sr.,LAC,31.0,203.20,USA,13.4,4.1,1.0,2020-21
11699,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,2020-21

In [ ]:
kagledf = kagledf[kagledf.season == '2020-21']
kagledf

In [62]:
final=pd.merge(kagledf,dftest1,how='inner',left_on='player_name',right_on='Player')

/var/folders/mv/pzkkwg_132x_kq3wgrqvf2jr0000gn/T/ipykernel_40241/255687820.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'season_y'} in the result is deprecated and will raise a MergeError in a future version.
  final=pd.merge(kagledf,dftest1,how='inner',left_on='player_name',right_on='Player')