In [ ]:
import requests
import pandas as pd
import json

In [8]:
url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2020"

querystring = {"page":"0","per_page":"100"}

headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
    'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

response = requests.get(url, headers=headers, params=querystring)

print(response.text[-80:])

l_pages":317,"current_page":1,"next_page":2,"per_page":100,"total_count":31657}}

In [48]:
stl = []
dreb = []
first_name=[]
last_name=[]

for i in range(318):

    url = "https://free-nba.p.rapidapi.com/stats?seasons[]=2020"

    querystring = {"page":"{i}","per_page":"100"}

    headers = {'x-rapidapi-host': "free-nba.p.rapidapi.com",
               'x-rapidapi-key': "0a58c448e1msh42682201a62cc30p1ea6c2jsnb4992c5a1579"}

    result = requests.get(url, headers=headers, params=querystring)
    
    data = result.json()
    
    for i in range(len(data['data'])):
        
        stl.append(data['data'][i]['stl'])
        
        dreb.append(data['data'][i]['dreb'])
        
        first_name.append(data['data'][i]['player']['first_name'])
        
        last_name.append(data['data'][i]['player']['last_name'])

In [50]:
df = pd.DataFrame(list(zip(first_name, last_name,stl,dreb)),
               columns =['First Name', 'Last Name','STL','DREB'])

In [55]:
df['Player']=df['First Name']+' '+ df['Last Name']

In [71]:
df=df[['Player','STL','DREB']]
df

                        Player  STL  DREB
0                 Kevin Durant    3     4
1                   Jeff Green    1     0
2               DeAndre Jordan    1     9
3                Stephen Curry    2     1
4                 Kyrie Irving    0     3
...                        ...  ...   ...
31795            Terrence Ross    2     2
31796            Evan Fournier    2     4
31797  Michael Carter-Williams    0     1
31798                Raul Neto    0     0
31799               Khem Birch    0     5

[31800 rows x 3 columns]

In [58]:
kagle = pd.read_csv('all_seasons_2.csv')

In [64]:
kagledf = pd.DataFrame(kagle)

In [65]:
kagledf

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Travis Knight,LAL,22.0,213.36,106.594120,Connecticut,USA,1996,1,...,4.8,4.5,0.5,6.2,0.127,0.182,0.142,0.536,0.052,1996-97
1,1,Matt Fish,MIA,27.0,210.82,106.594120,North Carolina-Wilmington,USA,1992,2,...,0.3,0.8,0.0,-15.1,0.143,0.267,0.265,0.333,0.000,1996-97
2,2,Matt Bullard,HOU,30.0,208.28,106.594120,Iowa,USA,Undrafted,Undrafted,...,4.5,1.6,0.9,0.9,0.016,0.115,0.151,0.535,0.099,1996-97
3,3,Marty Conlon,BOS,29.0,210.82,111.130040,Providence,USA,Undrafted,Undrafted,...,7.8,4.4,1.4,-9.0,0.083,0.152,0.167,0.542,0.101,1996-97
4,4,Martin Muursepp,DAL,22.0,205.74,106.594120,None,USA,1996,1,...,3.7,1.6,0.5,-14.5,0.109,0.118,0.233,0.482,0.114,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,11695,Matthew Dellavedova,CLE,30.0,190.50,90.718400,St.Mary's College of California,Australia,Undrafted,Undrafted,...,2.8,1.8,4.5,-3.1,0.029,0.085,0.125,0.312,0.337,2020-21
11696,11696,Maurice Harkless,SAC,28.0,200.66,99.790240,St. John's,USA,2012,1,...,5.2,2.4,1.2,-2.9,0.017,0.097,0.114,0.527,0.071,2020-21
11697,11697,Max Strus,MIA,25.0,195.58,97.522280,DePaul,USA,Undrafted,Undrafted,...,6.1,1.1,0.6,-4.2,0.011,0.073,0.179,0.597,0.074,2020-21
11698,11698,Marcus Morris Sr.,LAC,31.0,203.20,98.883056,Kansas,USA,2011,1,...,13.4,4.1,1.0,4.2,0.025,0.133,0.194,0.614,0.056,2020-21
11699,11699,Aaron Gordon,DEN,25.0,203.20,106.594120,Arizona,USA,2014,1,...,12.4,5.7,3.2,2.1,0.055,0.150,0.204,0.547,0.165,2020-21

In [72]:
kagledf=kagledf[['player_name','team_abbreviation','age','player_height','country','pts','reb','ast','season']]
kagledf

,player_name,team_abbreviation,age,player_height,country,pts,reb,ast,season
0,Travis Knight,LAL,22.0,213.36,USA,4.8,4.5,0.5,1996-97
1,Matt Fish,MIA,27.0,210.82,USA,0.3,0.8,0.0,1996-97
2,Matt Bullard,HOU,30.0,208.28,USA,4.5,1.6,0.9,1996-97
3,Marty Conlon,BOS,29.0,210.82,USA,7.8,4.4,1.4,1996-97
4,Martin Muursepp,DAL,22.0,205.74,USA,3.7,1.6,0.5,1996-97
...,...,...,...,...,...,...,...,...,...
11695,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,2020-21
11696,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,2020-21
11697,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,2020-21
11698,Marcus Morris Sr.,LAC,31.0,203.20,USA,13.4,4.1,1.0,2020-21
11699,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,2020-21

In [77]:
kagledf = kagledf[kagledf.season == '2020-21']
kagledf

,player_name,team_abbreviation,age,player_height,country,pts,reb,ast,season
11160,Yogi Ferrell,LAC,28.0,182.88,USA,5.6,1.9,2.2,2020-21
11161,Zion Williamson,NOP,20.0,200.66,USA,27.0,7.2,3.7,2020-21
11162,Zeke Nnaji,DEN,20.0,205.74,USA,3.2,1.5,0.2,2020-21
11163,Zach LaVine,CHI,26.0,195.58,USA,27.4,5.0,4.9,2020-21
11164,Yuta Watanabe,TOR,26.0,205.74,Japan,4.4,3.2,0.8,2020-21
...,...,...,...,...,...,...,...,...,...
11695,Matthew Dellavedova,CLE,30.0,190.50,Australia,2.8,1.8,4.5,2020-21
11696,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,2020-21
11697,Max Strus,MIA,25.0,195.58,USA,6.1,1.1,0.6,2020-21
11698,Marcus Morris Sr.,LAC,31.0,203.20,USA,13.4,4.1,1.0,2020-21
11699,Aaron Gordon,DEN,25.0,203.20,USA,12.4,5.7,3.2,2020-21

In [78]:
final=pd.merge(kagledf,df,how='inner',left_on='player_name',right_on='Player')

In [81]:
final=pd.merge(kagledf,df,how='inner',left_on='player_name',right_on='Player')

In [84]:
final=final[['Player','team_abbreviation','age','player_height','country','pts','reb','ast','STL','DREB','season']]

In [86]:
final.drop_duplicates()

,Player,team_abbreviation,age,player_height,country,pts,reb,ast,STL,DREB,season
0,Zion Williamson,NOP,20.0,200.66,USA,27.0,7.2,3.7,1,10,2020-21
318,Goran Dragic,MIA,35.0,190.50,Slovenia,13.4,3.4,4.4,4,2,2020-21
636,Devontae Cacok,LAL,24.0,200.66,USA,2.0,1.6,0.1,0,0,2020-21
954,Duncan Robinson,MIA,27.0,200.66,USA,13.1,3.5,1.8,0,5,2020-21
1272,Eric Bledsoe,NOP,31.0,185.42,USA,12.2,3.4,3.8,1,2,2020-21
...,...,...,...,...,...,...,...,...,...,...,...
29892,LeBron James,LAL,36.0,205.74,USA,25.0,7.7,7.8,0,3,2020-21
30210,Marc Gasol,LAL,36.0,210.82,Spain,5.0,4.1,2.1,0,1,2020-21
30528,Markieff Morris,LAL,31.0,205.74,USA,6.7,4.4,1.2,0,3,2020-21
30846,Marquese Chriss,GSW,23.0,205.74,USA,6.5,6.5,1.0,0,5,2020-21
31164,Maurice Harkless,SAC,28.0,200.66,USA,5.2,2.4,1.2,0,2,2020-21